In [1]:

#  Q1. Create a 1D NumPy Array: 
# ------------------------------
#  Create a 1D NumPy array named temperatures_w1 for Week 1 with the following values: [22.5, 25.3, 20.8, 23.4, 26.1,
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:
# Q2. Inspection and Properties: 
# ------------------------------
# ● Inspect the shape, data type, and the number of elements in the array.Inspect the shape of the temperatures_w1 array.

print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)

Shape: (7,)
Data Type: float64
Number of Elements: 7


In [3]:
# Q3. Array Operations:
# ----------------------
# ● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula: Fahrenheit = (Celsius * 9/5) + 32
# ● Find the maximum, minimum, and mean temperatures for the week.


# Convert Celsius to Fahrenheit
temperatures_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:")
print(temperatures_f)

# Find Maximum, Minimum and Mean Temperature

maximum_temp = np.max(temperatures_w1)
minimum_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Maximum Temperature:", maximum_temp)
print("Minimum Temperature:", minimum_temp)
print("Mean Temperature:", mean_temp)

Temperatures in Fahrenheit:
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


In [4]:
# Q4. Array Slicing and Indexing:
# --------------------------------
# ● Extract the temperatures for the first three days of the week.
# ● Extract the temperatures for the weekend (last two days).
# ● Extract the temperatures for the middle three days of the week.


# First Three Days

first_three_days = temperatures_w1[:3]

print("First Three Days:")
print(first_three_days)

# Weekend — Last Two Days

weekend = temperatures_w1[-2:]

print("Weekend:")
print(weekend)

# Middle Three Days

middle_three_days = temperatures_w1[2:5]

print("Middle Three Days:")
print(middle_three_days)

First Three Days:
[22.5 25.3 20.8]
Weekend:
[24.8 21.9]
Middle Three Days:
[20.8 23.4 26.1]


In [6]:
# Q5. Create a 2D Array:
# ----------------------
# Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
# ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
# ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print("2D Temperature Array:")
print(temperatures)

2D Temperature Array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [7]:
# Q6. Inspect and Slice the 2D Array:
# --------------------------------
# ● Inspect and print the shape, data type, and total number of elements in the temperatures array.
# ● Extract the temperatures for each week and the weekends (last two days) for both weeks.


#Inspect Shape, Data Type and Total Number of Elements

print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)


#Extract Temperatures for Each Week

week1 = temperatures[0]
week2 = temperatures[1]

print("Week 1 Temperatures:")
print(week1)

print("\nWeek 2 Temperatures:")
print(week2)

#Extract Weekend Temperatures for Both Weeks

week1_weekend = temperatures[0, -2:]
week2_weekend = temperatures[1, -2:]

print("Week 1 Weekend:")
print(week1_weekend)

print("\nWeek 2 Weekend:")
print(week2_weekend)


Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14
Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 Temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 Weekend:
[24.8 21.9]

Week 2 Weekend:
[22.8 20.1]


In [8]:
# ===================
#   Pandas Series:
# =================


# Q1. Creating Pandas Series:
# ● Create a Pandas Series named marks with the following data:
# ➢ Marks: 95, 92, 89, 85, 80
# ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

import pandas as pd

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print("Marks Series:")
print(marks)

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [9]:
# Q2. Indexing and Slicing:
# ------------------------
# ● Use the integer index position to access the mark of the 1st rank student.
# ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
# ● Use the iloc accessor to retrieve the mark of the 3rd rank student.
# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

#Integer Index Position — 1st Rank

first_rank = marks.iloc[0]

print("Mark of 1st Rank Student:", first_rank)

#loc — Top 3 Ranks

top_three = marks.loc[['Rank1', 'Rank2', 'Rank3']]

print("Top 3 Ranks:")
print(top_three)

#iloc — 3rd Rank

third_rank = marks.iloc[2]

print("Mark of 3rd Rank Student:", third_rank)

#Boolean Mask — Marks Greater Than 90

marks_above_90 = marks[marks > 90]

print("Ranks with Marks Greater Than 90:")
print(marks_above_90)

Mark of 1st Rank Student: 95
Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64
Mark of 3rd Rank Student: 89
Ranks with Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


In [10]:
# Q3. Manipulating Series:
# --------------------------
# ● Modify the mark of the student with the 1st rank to 100.
# ● Remove the entry corresponding to the last rank from the Series.
# ● Compute the CGPA by dividing each mark in the Series by 10.
#Modify 1st Rank Mark to 100

marks.loc['Rank1'] = 100

print("Updated Marks Series:")
print(marks)

#Remove Last Rank

marks = marks.drop('Rank5')

print("Series After Removing Last Rank:")
print(marks)
#Calculate CGPA

cgpa = marks / 10

print("CGPA:")
print(cgpa)

Updated Marks Series:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Series After Removing Last Rank:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [11]:
# ======================
#   Pandas DataFrame:
# ======================

# Q1. Creating Pandas DataFrame:
# ● Create a Pandas DataFrame named transactions with the following data:
# ➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
# ➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture','Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
# ➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West','South', 'North'
# ➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [12]:
# Q2. Data Exploration:
# ----------------------
# ● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
# ● Display only the 'ProductCategory' and 'Amount' columns.
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
# ● Find the value counts for the 'ProductCategory' column.
# ● Find the unique values in the 'Region' column.
# ● Group by 'Region' and find the mean amount for each region.

#Display DataFrame
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [13]:
#Display Head
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [14]:
#Display Tail
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [16]:
#Shape
print("Shape:", transactions.shape)

Shape: (10, 4)


In [17]:
#Column Names
print("Column Names:")
print(transactions.columns)

Column Names:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [18]:
#Data Types
print("Data Types:")
print(transactions.dtypes)

Data Types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [19]:
#Basic Information
transactions.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [20]:
#Display ProductCategory and Amount
print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [21]:
#Retrieve Last 3 Columns Using iloc
last_three_columns = transactions.iloc[:, -3:]

print(last_three_columns)

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [22]:
#Filter North Region and Amount Greater Than 200
filtered_transactions = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_transactions)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [23]:
#Value Counts for ProductCategory
product_counts = transactions['ProductCategory'].value_counts()

print(product_counts)

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [24]:
#Unique Values in Region
unique_regions = transactions['Region'].unique()

print("Unique Regions:")
print(unique_regions)

Unique Regions:
['North' 'South' 'East' 'West']


In [25]:
#Group by Region and Find Mean Amount
region_mean = transactions.groupby('Region')['Amount'].mean()

print("Mean Amount by Region:")
print(region_mean)

Mean Amount by Region:
Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [26]:
# Q3. Manipulating the DataFrame:
# --------------------------------
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.
# ● Remove the row with TransactionID 109.
# ● Delete the 'Discount' column from the DataFrame.

#Modify TransactionID 102 Amount to 165
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [27]:
#Add Discount Column — 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [28]:
#Remove TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
]

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [29]:
#Delete Discount Column
transactions = transactions.drop(columns='Discount')

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
